### ISSUE TITLE
Provide and use a top-left snapper

### ISSUE THREAD

**Issue by planger** [eclipse-glsp/glsp-examples#27]
With https://github.com/eclipse-glsp/glsp-examples/pull/26 we use the `CenterGridSnapper`. However, this is not really ideal for the example, as all nodes have different widths as the width depends on the label. Thus, you can't horizontally align the nodes manually with this snapper anymore.

We should add and use a top-left-based snapper for such cases.

**Comment by tortmayr** [comment]
already addressed with #26
