### ISSUE TITLE
POM missing no dependency information available

### ISSUE THREAD

**Issue by TRworkspace** [eclipse-glsp/glsp-examples#72]
The following error happens when I try to build the minimal example:

MacOs
Java version: 11.0.2
Node version: 12.14.1
Maven version: 3.6.3

`[WARNING] The POM for org.eclipse.glsp:org.eclipse.glsp.server:jar:0.8.0-SNAPSHOT is missing, no dependency information available
Downloading from sonatype: https://oss.sonatype.org/content/groups/public/org/eclipse/glsp/org.eclipse.glsp.server/0.8.0-SNAPSHOT/org.eclipse.glsp.server-0.8.0-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.379 s
[INFO] Finished at: 2021-01-17T17:31:08+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project org.eclipse.glsp.example.minimal: Could not resolve dependencies for project org.eclipse.glsp.example:org.eclipse.glsp.example.minimal:jar:0.8.0: Could not find artifact org.eclipse.glsp:org.eclipse.glsp.server:jar:0.8.0-SNAPSHOT in sonatype (https://oss.sonatype.org/content/groups/public) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
`

**Comment by tortmayr** [comment]
Thanks for raising this issue. It looks like we are still using an old snapshot version of GLSP in the minimal example Server. I have created a PR to fix this. Should be working again as soon as https://github.com/eclipse-glsp/glsp-examples/commit/ddbdd9130ec977bb6b629a638d9f5229aa01289f is merged.

**Comment by GrosuSergiu65** [comment]
I got the same problem 
[WARNING] The POM for org.psychologicalTestSubject:testingUtils:jar:1.0-SNAPSHOT is missing, no dependency information available

tortmayr how did you resolve it?
